apiVersion: apps/v1
kind: Deployment

metadata:
  name: employee-app

spec:
  replicas: 2

  selector:
    matchLabels:
      app: employee-app

  template:
    metadata:
      labels:
        app: employee-app

    spec:
      containers:
      - name: employee-app
        image: image: 465768367809.dkr.ecr.ap-south-1.amazonaws.com/employee-app:v1

        envFrom: 
        - configMapRef: 
            name: employee-config
        - secretRef: 
            name: employee-secret

        ports:
        - containerPort: 5000
     
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"

        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 5

        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5